import ExpansionComponent from "@/components/Chat/ExpansionComponent";
import ChatCodeInterpreter from "@/components/Chat/ChatContentBlocks/ChatCodeInterpreter";
import React from "react";


interface FileInfo {
    type: string;
    values: {
      file_key: string;
      presigned_url: string;
      file_size: number;
      file_key_low_res?: string;
      presigned_url_low_res?: string;
    };
  }


interface Props {
    messageIsStreaming: boolean;
    message: any;
}

const ChatCodeInterpreterFileBlock: React.FC<Props> = ({ message, messageIsStreaming }) => {

    const error = message.data?.state?.codeInterpreter?.error;
    const files = message.data?.state?.codeInterpreter?.content ?? [];

    if (messageIsStreaming || (files.length === 0 && !error)) {
        return <></>;
    }

    return <div className="mt-3">
                {files.length > 0 &&
                <ExpansionComponent title="Generated Files"
                    content={files.map((file: FileInfo, index: number) => (
                        <ChatCodeInterpreter key={index} file_info={file} />
                ))}/>}
                {error &&
                <label className="text-red-500">
                    An error occurred with the code interpreter. The response was generated by Amplify.
                </label>}
            </div>;
};

export default ChatCodeInterpreterFileBlock;


